<a href="https://colab.research.google.com/github/JaganRaja/pytorch_basics/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#jk

In [1]:
import torch

In [ ]:
# tensors
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
type([4])

list

In [ ]:
t1.dtype

torch.float32

In [ ]:
a1 = torch.tensor(4)
a1.dtype

torch.int64

In [ ]:
# vector

t2 = torch.tensor([1.,2.,3.,6])
t2

tensor([1., 2., 3., 6.])

In [ ]:
t2.dtype

torch.float32

In [ ]:
# Matrix

t3 = torch.tensor(
    [
     [4.,5.,9.],
     [7.,8.,9.],
     [1.,2.,3.],

    ]
)
t3

tensor([[4., 5., 9.],
        [7., 8., 9.],
        [1., 2., 3.]])

In [ ]:
  # 3-dim tensors

  t4 = torch.tensor([
                     [[11,23,45],
                      [10,9.,8]],
                     [[41.,23,5],
                      [11,90,80]]
  
                
  ])

  t4

tensor([[[11., 23., 45.],
         [10.,  9.,  8.]],

        [[41., 23.,  5.],
         [11., 90., 80.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 6.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[4., 5., 9.],
        [7., 8., 9.],
        [1., 2., 3.]])


torch.Size([3, 3])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 23., 45.],
         [10.,  9.,  8.]],

        [[41., 23.,  5.],
         [11., 90., 80.]]])


torch.Size([2, 2, 3])

In [ ]:

t5 = torch.tensor(
    [
     [4.,5.,9.],
     [7.,8.]

    ]
)
t5

ValueError: ignored

In [ ]:
# tensors operations

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)   # trainable parameter so requires_grad=True
b = torch.tensor(5., requires_grad=True)   # trainable parammeter so requires_grad=True

x,w,b


(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# arithmetic

y = w * x + b

In [ ]:
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# to find the gradient
y.backward()

In [ ]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
# tensor function

# creating matirx
t6 = torch.full((3,2), 22)
t6

tensor([[22, 22],
        [22, 22],
        [22, 22]])

In [ ]:
t6 = torch.full((3,3), 0)
t6

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
# concat

t7 = torch.cat((t3, t6))
t7

tensor([[4., 5., 9.],
        [7., 8., 9.],
        [1., 2., 3.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
t8 = torch.sin(t7)
t8

tensor([[-0.7568, -0.9589,  0.4121],
        [ 0.6570,  0.9894,  0.4121],
        [ 0.8415,  0.9093,  0.1411],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [ ]:
t9 = t8.reshape(3,6,1)
t9

tensor([[[-0.7568],
         [-0.9589],
         [ 0.4121],
         [ 0.6570],
         [ 0.9894],
         [ 0.4121]],

        [[ 0.8415],
         [ 0.9093],
         [ 0.1411],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]],

        [[ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000],
         [ 0.0000]]])

In [ ]:
# interoperability with numpy

import numpy as np

x = np.array([[1,3], [8,7]])

x

array([[1, 3],
       [8, 7]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1, 3],
        [8, 7]])

In [ ]:
y.numpy()

array([[1, 3],
       [8, 7]])

In [ ]:
# Linear regression

In [ ]:
 !nvidia-smi

Mon Apr 25 14:17:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   74C    P8    34W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import numpy as np
import torch

In [ ]:
# input data
input = np.array([[32, 55, 77],
                  [31, 75, 57],
                  [52, 55, 77],
                  [22, 100, 87],
                  [62, 80, 77]
                  ], dtype='float32')
input

array([[ 32.,  55.,  77.],
       [ 31.,  75.,  57.],
       [ 52.,  55.,  77.],
       [ 22., 100.,  87.],
       [ 62.,  80.,  77.]], dtype=float32)

In [ ]:
# target
targets = np.array([
                    [32,66],
                    [52,76],
                    [102,155],
                    [32,26],
                    [99,100]
                    ], dtype='float32')

targets

array([[ 32.,  66.],
       [ 52.,  76.],
       [102., 155.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [ ]:
input = torch.from_numpy(input)
targets = torch.from_numpy(targets)

print(input)
print(targets)

tensor([[ 32.,  55.,  77.],
        [ 31.,  75.,  57.],
        [ 52.,  55.,  77.],
        [ 22., 100.,  87.],
        [ 62.,  80.,  77.]])
tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])


In [ ]:
# weights & biases

w = torch.randn(2, 3, requires_grad=True)
w

tensor([[ 0.7730, -0.3888, -1.7635],
        [-0.1583,  1.4254,  1.5216]], requires_grad=True)

In [ ]:
b = torch.randn(2, requires_grad=True)
b

tensor([ 1.4330, -0.0300], requires_grad=True)

In [ ]:
# w transpose to multiply with x
# y = x * w^T + b

def model(x):
  return x @ w.t() + b


In [ ]:
preds = model(input)
print(preds)

tensor([[-131.0010,  190.4638],
        [-104.2798,  188.6976],
        [-115.5403,  187.2982],
        [-173.8611,  271.4044],
        [-117.5292,  221.3498]], grad_fn=<AddBackward0>)


In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

In [ ]:
# loss

def MSE(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()


In [ ]:
# compute the loss
loss = MSE(preds, targets)
loss

tensor(29176.4473, grad_fn=<DivBackward0>)

In [ ]:
# compute gradient
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[ 0.7730, -0.3888, -1.7635],
        [-0.1583,  1.4254,  1.5216]], requires_grad=True)
tensor([[ -7865.3110, -14111.8408, -14558.4590],
        [  4415.7114,  10264.5312,   9837.7119]])


In [ ]:
with torch.no_grad():
  w -= w.grad * 1e-5  # w(new) = w(old) - learning_rate * (de/dw)  .. here de -> loss function
  b -= b.grad * 1e-5  # b(new) = b(old) - learning_rate * (de/db)  .. here de -> loss function

In [ ]:
print(w) # weights changed.. based on above code

tensor([[ 0.8517, -0.2477, -1.6179],
        [-0.2024,  1.3227,  1.4232]], requires_grad=True)


In [ ]:

preds = model(input)
print(preds)


tensor([[-109.5107,  175.8289],
        [ -82.9574,  174.0216],
        [ -92.4769,  171.7802],
        [-145.3512,  251.6084],
        [ -90.1514,  202.8241]], grad_fn=<AddBackward0>)


In [ ]:
# compute the loss
loss = MSE(preds, targets)
loss

tensor(22671.5879, grad_fn=<DivBackward0>)

In [ ]:
# training 
n = 400
for i in range(n):
  preds = model(input)
  loss = MSE(preds, targets)

  loss.backward()

  with torch.no_grad():
    w -= w.grad * 1e-5 
    b -= b.grad * 1e-5 
    w.grad.zero_()
    b.grad.zero_()
  
  print(f"Epochs:  {i}/{n} ---- loss: {loss}")


Epochs:  0/400 ---- loss: 563.5936889648438
Epochs:  1/400 ---- loss: 562.12060546875
Epochs:  2/400 ---- loss: 560.6566162109375
Epochs:  3/400 ---- loss: 559.2015991210938
Epochs:  4/400 ---- loss: 557.75537109375
Epochs:  5/400 ---- loss: 556.3180541992188
Epochs:  6/400 ---- loss: 554.8895263671875
Epochs:  7/400 ---- loss: 553.4699096679688
Epochs:  8/400 ---- loss: 552.058837890625
Epochs:  9/400 ---- loss: 550.656494140625
Epochs:  10/400 ---- loss: 549.2626953125
Epochs:  11/400 ---- loss: 547.8773193359375
Epochs:  12/400 ---- loss: 546.5006103515625
Epochs:  13/400 ---- loss: 545.13232421875
Epochs:  14/400 ---- loss: 543.7723999023438
Epochs:  15/400 ---- loss: 542.4208374023438
Epochs:  16/400 ---- loss: 541.0775146484375
Epochs:  17/400 ---- loss: 539.7423706054688
Epochs:  18/400 ---- loss: 538.4154663085938
Epochs:  19/400 ---- loss: 537.0966796875
Epochs:  20/400 ---- loss: 535.7860107421875
Epochs:  21/400 ---- loss: 534.4832763671875
Epochs:  22/400 ---- loss: 533.188

In [ ]:
preds = model(input)
preds

tensor([[ 43.4630,  83.6423],
        [ 54.0832,  50.2256],
        [ 82.8059, 119.8544],
        [ 28.9672,  41.3576],
        [107.6906, 119.7870]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102., 155.],
        [ 32.,  26.],
        [ 99., 100.]])

In [2]:
# Using Torch built in function for linear regression

import torch.nn as nn
import numpy as np
import pandas as pd

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')


targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
# DataLoader  -- helps to create a batch

from torch.utils.data import TensorDataset

In [5]:
train_ds = TensorDataset(inputs, targets)

In [6]:
train_ds[0]  # o/p will be in tuple format.. it will be useful for DataLoader function

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [7]:
train_ds[0:3]  # o/p will be in tuple format.. it will be useful for DataLoader function

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [8]:
from torch.utils.data import DataLoader

In [9]:
batch_size = 5
train_data = DataLoader(train_ds, batch_size, shuffle=True)

In [10]:
train_data

In [11]:
for xb, yb in train_data:
  print(xb)
  print(yb)
  break

tensor([[103.,  43.,  36.],
        [ 68.,  96.,  71.],
        [ 88., 134.,  59.],
        [ 68.,  97.,  70.],
        [ 74.,  66.,  43.]])
tensor([[ 20.,  38.],
        [104., 118.],
        [118., 132.],
        [102., 120.],
        [ 57.,  69.]])


In [12]:
## nn.linear

# define model

model = nn.Linear(3, 2)

print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2075, -0.1524, -0.2930],
        [-0.4856,  0.1673, -0.2900]], requires_grad=True)
Parameter containing:
tensor([-0.1407,  0.0948], requires_grad=True)


In [13]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2075, -0.1524, -0.2930],
         [-0.4856,  0.1673, -0.2900]], requires_grad=True),
 Parameter containing:
 tensor([-0.1407,  0.0948], requires_grad=True)]

In [14]:
preds = model(inputs)
preds

tensor([[ -7.8034, -36.6135],
        [-13.4216, -47.9310],
        [-19.5048, -36.5534],
        [  3.6294, -52.9692],
        [-20.9633, -37.6508],
        [ -7.4435, -37.2663],
        [-13.5621, -48.3883],
        [-19.5903, -37.3289],
        [  3.2695, -52.3163],
        [-21.4638, -37.4553],
        [ -7.9440, -37.0708],
        [-13.0617, -48.5839],
        [-19.3643, -36.0960],
        [  4.1298, -53.1647],
        [-21.3232, -36.9980]], grad_fn=<AddmmBackward0>)

In [15]:
import torch.nn.functional as F
loss_fn = F.mse_loss


In [16]:
loss = loss_fn(preds, targets)

In [17]:
loss

tensor(14280.1934, grad_fn=<MseLossBackward0>)

In [18]:
# optimizer

opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [19]:
# training loop

def fit(num_epochs, model, loss_fn, opt, train_data):
  for epoch in range(num_epochs):
    for xb, yb in train_data:
      pred = model(xb)
      loss = loss_fn(pred, yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    
    if (epoch+1) % 10 == 0:
      print("Epoch [{}/{}], Loss: {:.4f}".format(epoch+1, num_epochs, loss))

In [20]:
fit(100, model, loss_fn, opt, train_data)

Epoch [10/100], Loss: 408.4560
Epoch [20/100], Loss: 460.0863
Epoch [30/100], Loss: 206.2973
Epoch [40/100], Loss: 241.0512
Epoch [50/100], Loss: 107.5000
Epoch [60/100], Loss: 106.0562
Epoch [70/100], Loss: 69.6916
Epoch [80/100], Loss: 53.1560
Epoch [90/100], Loss: 54.4281
Epoch [100/100], Loss: 26.3190


In [21]:
pred = model(inputs)
pred

tensor([[ 58.7609,  71.4380],
        [ 79.8197,  97.0053],
        [121.0034, 140.2381],
        [ 30.5831,  42.4296],
        [ 92.2350, 109.5676],
        [ 57.6810,  70.3415],
        [ 79.1442,  96.3782],
        [121.0708, 140.4636],
        [ 31.6630,  43.5261],
        [ 92.6395, 110.0369],
        [ 58.0854,  70.8108],
        [ 78.7397,  95.9089],
        [121.6790, 140.8652],
        [ 30.1786,  41.9603],
        [ 93.3150, 110.6640]], grad_fn=<AddmmBackward0>)

In [22]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [23]:
model(torch.tensor([[75,66,44.]]))

tensor([[57.7483, 70.5671]], grad_fn=<AddmmBackward0>)

In [24]:
pred

tensor([[ 58.7609,  71.4380],
        [ 79.8197,  97.0053],
        [121.0034, 140.2381],
        [ 30.5831,  42.4296],
        [ 92.2350, 109.5676],
        [ 57.6810,  70.3415],
        [ 79.1442,  96.3782],
        [121.0708, 140.4636],
        [ 31.6630,  43.5261],
        [ 92.6395, 110.0369],
        [ 58.0854,  70.8108],
        [ 78.7397,  95.9089],
        [121.6790, 140.8652],
        [ 30.1786,  41.9603],
        [ 93.3150, 110.6640]], grad_fn=<AddmmBackward0>)

In [25]:
y_pred = pred.numpy()
y_pred

RuntimeError: ignored

In [26]:
from sklearn.metrics import r2_score
y_pred = pred.numpy()
targets = targets.numpy()
r2_score(pred, targets)

RuntimeError: ignored

In [27]:
# to save the model

torch.save(model.state_dict(), 'model_weights.pth')

In [29]:
# load the model

model = torch.load('model_weights.pth')